title: Ellipses Heaven
author: Roland Christensen
email: CodingByVoices@gmail.com
description: > # this means to ignore newlines until next key. AKA muliti-line formatting.
  Google should ignore this silly little site. 
  It is only about ellipes. Who really cares about ellipses?

# social links
github_username:  RolandChristensen # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
